# CI/CD Configuration File
# This file contains configuration settings for the PhishGuard CI/CD pipeline
# 
# Note: This is a configuration file, not a GitHub Actions workflow.
# The actual workflows are defined in:
# - ci-cd-pipeline.yml (main CI/CD pipeline)
# - quality.yml (code quality checks)
# - security.yml (security scanning)
# - deploy.yml (deployment automation)
#
# Configuration settings are embedded within each workflow file
# to ensure proper GitHub Actions validation. 