name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * 1'  # Run weekly on Mondays at 2 AM

jobs:
  # Dependency Vulnerability Scan
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install safety
      run: pip install safety

    - name: Run Python dependency scan
      run: |
        safety check --json --output safety-report.json || true
        safety check --full-report

    - name: Run npm audit
      working-directory: ./frontend
      run: |
        npm audit --audit-level=moderate --json > npm-audit.json || true
        npm audit --audit-level=moderate

    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: dependency-security-reports
        path: |
          safety-report.json
          frontend/npm-audit.json

  # Code Security Scan
  code-scan:
    name: Code Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit security scan
      run: |
        bandit -r backend/src/ -f json -o bandit-report.json || true
        bandit -r backend/src/ -f txt

    - name: Install Semgrep
      run: |
        python -m pip install semgrep

    - name: Run Semgrep scan
      run: |
        semgrep ci --config auto --json --output semgrep-report.json || true
        semgrep ci --config auto

    - name: Upload code security reports
      uses: actions/upload-artifact@v3
      with:
        name: code-security-reports
        path: |
          bandit-report.json
          semgrep-report.json

  # Container Security Scan
  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend image
      run: docker build -t phishguard-backend:test ./backend

    - name: Build frontend image
      run: docker build -t phishguard-frontend:test ./frontend

    - name: Install Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'phishguard-backend:test'
        format: 'sarif'
        output: 'trivy-backend-results.sarif'

    - name: Scan frontend image
      run: |
        trivy image --format sarif --output trivy-frontend-results.sarif phishguard-frontend:test

    - name: Upload container security reports
      uses: actions/upload-artifact@v3
      with:
        name: container-security-reports
        path: |
          trivy-backend-results.sarif
          trivy-frontend-results.sarif

  # Secret Scanning
  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install TruffleHog
      run: |
        pip install trufflehog

    - name: Run TruffleHog scan
      run: |
        trufflehog --json . > trufflehog-report.json || true
        trufflehog .

    - name: Upload secret scan reports
      uses: actions/upload-artifact@v3
      with:
        name: secret-scan-reports
        path: trufflehog-report.json

  # Security Report Generation
  security-report:
    name: Generate Security Report
    runs-on: ubuntu-latest
    needs: [dependency-scan, code-scan, container-scan, secret-scan]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all security reports
      uses: actions/download-artifact@v3
      with:
        path: security-reports

    - name: Generate security summary
      run: |
        echo "# Security Scan Summary" > security-summary.md
        echo "Generated on: $(date)" >> security-summary.md
        echo "" >> security-summary.md
        
        echo "## Dependency Vulnerabilities" >> security-summary.md
        if [ -f "security-reports/dependency-security-reports/safety-report.json" ]; then
          echo "✅ Python dependencies scanned" >> security-summary.md
        else
          echo "❌ Python dependency scan failed" >> security-summary.md
        fi
        
        if [ -f "security-reports/dependency-security-reports/npm-audit.json" ]; then
          echo "✅ Node.js dependencies scanned" >> security-summary.md
        else
          echo "❌ Node.js dependency scan failed" >> security-summary.md
        fi
        
        echo "" >> security-summary.md
        echo "## Code Security Issues" >> security-summary.md
        if [ -f "security-reports/code-security-reports/bandit-report.json" ]; then
          echo "✅ Bandit security scan completed" >> security-summary.md
        else
          echo "❌ Bandit security scan failed" >> security-summary.md
        fi
        
        if [ -f "security-reports/code-security-reports/semgrep-report.json" ]; then
          echo "✅ Semgrep security scan completed" >> security-summary.md
        else
          echo "❌ Semgrep security scan failed" >> security-summary.md
        fi
        
        echo "" >> security-summary.md
        echo "## Container Security" >> security-summary.md
        if [ -f "security-reports/container-security-reports/trivy-backend-results.sarif" ]; then
          echo "✅ Backend container scanned" >> security-summary.md
        else
          echo "❌ Backend container scan failed" >> security-summary.md
        fi
        
        if [ -f "security-reports/container-security-reports/trivy-frontend-results.sarif" ]; then
          echo "✅ Frontend container scanned" >> security-summary.md
        else
          echo "❌ Frontend container scan failed" >> security-summary.md
        fi

    - name: Upload security summary
      uses: actions/upload-artifact@v3
      with:
        name: security-summary
        path: security-summary.md

    - name: Create security issue on failure
      uses: actions/github-script@v7
      if: failure()
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Security vulnerabilities detected',
            body: 'Security scan detected vulnerabilities. Please check the security reports for details.',
            labels: ['security', 'bug']
          }) 